import Head from "next/head";
import Form from "../components/Search/Form";
import AppLayout from "../components/Layout/AppLayout";

export default function Home() {
  return (
    <AppLayout className="rounded-xl shadow-lg m-16">
      <Head>
        <title>Booking App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center">
        <Form />
      </main>
    </AppLayout>
  );
}
